apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: anfnp58nq-go 
  janus-idp.io/tekton: anfnp58nq-go
  backstage.io/kubernetes-id: anfnp58nq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: anfnp58nq-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml