apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: anfnp58nq-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:e1d2039719f6b0674a1bb851eb50a78128d39541@sha256:52b2f0c5ea40f8e1e685ac36fb72c02778f916d578371a11ec54bf9d6387fe49
          name: container-image
